title: IASG's Help Site
description: An under construction website for hosting information about the Cyber Defense Competition
github_username: IASG
youtube_channel: UC-rLOtGfHGx9N1mlNNEwJNQ
discord: https://discord.gg/3xxec7V5zN
theme: just-the-docs
color_scheme: dark
favicon_ico: "/assets/images/favicon.ico"

footer_content: "<p>This is a test</p>"

url: https://iasg.github.io/CDCHelpSite/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
