title: IASG Cyber Defense Compeition Help Site
description: An under construction website for hosting information about the Cyber Defense Competition
theme: just-the-docs

url: https://iasg.github.io/CDCHelpSite/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
