title: IASG Cyber Defense Competition Help Site
description: An under construction website for hosting information about the Cyber Defense Competition
theme: just-the-docs
color_scheme: dark

url: https://iasg.github.io/CDCHelpSite/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  warning:
    title: Warning
    color: red
  information:
    title: Information
    color: purple
  cli:
    title: CLI
    color: yellow
  